services:

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    # Apply the configuration above to save database. Don't forget exclude this folder from version controller (includes on gitignore, for example)
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    #   - ./.docker/dbdata:/var/lib/mysql  